/* What this program is:
 * A test to confirm that our sine wave formula produces correct numbers before we commit it to a WAV file.
 * 
 * What is does, step by step:
 * Defines three constants: the sample rate (44100 samples/sec), the frequency of A4 (440 Hz), and the maximum
 * amplitude (32767) 
 * Loops through the first 100 samples indices (i = 0, 1, 2, ... 9)
 * For each sample index, converts i into real time in seconds by dividing by the sample rate -
 * so i=0 corresponds to t=0.0s, i=44100 would be t=1.0s.
 * Plugs that time value into the sine wave formula to get a number between -1.0 and +1.0.
 * Scales that number to the maximum amplitude (32767) to convert it from a floating-point fraction into a 16-bit
 * integer that a WAV file can store.
 * Prints the result so we can visually verify the wave is behaving correctly - starting near 0, rising, cycling. 
 */

#include <stdio.h> // for printf()
#include <math.h> // for sin() and M_PI
#include <stdint.h> // for int16_t

// teach me about <stdint.h> - it is a header file in the C standard library. What is a header file? A header file is a file that contains declarations of functions, macros, contants, and data types that can be shared across multiple source files. What's the difference between a hader file and a library? A header file provides the interface (declarations) for functions and data types, while a library contains the actual implementation (definitions) of those functions. How do I use a header file? You include it in your source code using the #include directive, which allows you to access the declarations and definitions provided in the header file. What is <stdint.h> specifically? <stdint.h> is a header file that defines fixed-width integer types, such as int8_t, int16_t, int32_t, and their unsigned counterparts. These types provide a consistent way to represent integers of specific sizes across different platforms and compilers.

// Should we start by defining the constants? Yes, Let's define the constants for sample rate, frequency and maximum amplitude.

#define SAMPLE_RATE 44100 // samples per second
#define FREQUENCY 440.0 // frequency of A4 in Hz
#define MAX_AMPLITUDE 32767 // maximum amplitude for 16-bit signed integer

int main(void) { // What does int main(void) mean? It is the entry point of a C program. The int indicates that the function returns an integer value, which is typically used to indicate the success or failure of the program. The void indicates that the function does not take any arguments. What happens if we change it to int main(int argc, char *argv[])? Changing it to int main(int argc, char *argv[]) allows the program to accept command-line arguments. argc is an integer that represents the number of arguments passed to the program, and argv is an array of strings (character pointers) that contains the actual arguments. This can be useful for passing input parameters or options to the program when it is executed from the command line. Why aren't we using command-line arguments in this program? We are not using command-line arguments in this program because it is a simple test that does not require any input parameters. The program is designed to generate and print sine wave sample values based on predefined constants, so there is no need for additional input from the user. However, if we wanted to make the program more flexible, we could modify it to accept command-line arguments for sample rate, frequency, or amplitude.
    for (int i = 0; i < 10; i++) { // what is "int i = 0?" It initializes the loop variable i to 0. Why specifically? We start at 0 because we want to generate the first 10 samples of the sine wave, and array indices in C are zero-based. What is i++? It increments the loop variable i by 1 after each iteration of the loop. How could it be different? Is there i--, for example? Yes, i-- would decrement the loop variable i by 1 after each iteration. We could also use other increment/decrement expressions, such as i += 2 to increment by 2 or i -= 3 to decrement by 3. The choice of increment/decrement depends on the specific requirements of the loop and what we want to achieve with the iteration.
        double time_sec = (double)i / SAMPLE_RATE; // why 'double'? We use double to represent the time variable t as a floating-point number with double precision. Can I use "time" instead of "t"? Yes, you can use "time" instead of "t" as the variable name. However, "time" is a common function name in C, so using it as a variable name may lead to confusion or conflicts. Using a shorter name like "t" helps avoid potential issues and keeps the code concise. What about time_(something)? Yes, you can use a variable name like "time_value" or "time_sec" to make it more descriptive while avoiding conflicts with the standard library function "time". The choice of variable name should be clear and meaningful to indicate its purpose in the code.
        int16_t sample_value = (int16_t)(MAX_AMPLITUDE * sin(2.0 * M_PI * FREQUENCY * time_sec)); // why int16_t? We use int16_t to represent the sample value as a 16-bit signed integer. Does that mean the value can range from -32768 to 32767? Yes. -32768 to 32767 what are those? bits or bytes? You say it's "values" but what "values" specifically? The values refer to the range of possible integer values that can be represented by a 16-bit signed integer. In this case, the range is from -32768 to 32767, which corresponds to the minimum and maximum values that can be stored in a 16-bit signed integer. These values are not bits or bytes themselves, but rather the numerical range that can be represented using 16 bits of memory. The negative values represent the lower half of the range, while the positive values represent the upper half. The total number of distinct values that can be represented is 2^16 = 65536, which includes both negative and positive values as well as zero.
        printf("Sample %d: %d\n", i, sample_value); // why "i"? We use "i" to indicate the sample index in the output. It helps us identify which sample value corresponds to which index in the loop.
    }
    return 0; // Can I return something else? Yes, you can return other integer values to indicate different exit statuses. By convention, returning 0 indicates successful execution, while returning a non-zero value indicates an error or abnormal termination. For example, you could return 1 to indicate a general error, or use specific values to represent different types of errors in your program. The choice of return value depends on how you want to communicate the program's outcome to the operating system or calling process. If I don't return 1, how will I know if the program failed? You can check the return value of the program in the command line or terminal after it finishes executing. In most operating systems, you can use the special variable $? (in Unix-like systems) or %ERRORLEVEL% (in Windows) to check the exit status of the last executed command. If the return value is 0, it indicates success; if it is non-zero, it indicates an error. You can also implement error handling in your program to provide more detailed information about what went wrong, such as printing error messages or logging errors to a file. I'm using Ubuntu WSL, how do I check the return value? 
    // In Ubuntu WSL, you can check the return value of the last executed command by using the special variable $?. After running your program, simply type echo $? in the terminal and press Enter. This will display the exit status of the last command. If it returns 0, it means the program executed successfully. If it returns a non-zero value, it indicates that an error occurred during execution.    
}

// Why is AMPLITUDE exactly 32767? The maximum amplitude of 32767 is chosen because it is the maximum positive value that can be represented by a 16-bit signed integer. In a 16-bit signed integer, the range of values is from -32768 to 32767. By using the maximum positive value, we ensure that the sine wave can utilize the full dynamic range of the audio format, allowing for the highest possible volume without clipping or distortion. This choice provides a good balance between audio quality and file size, as it allows for a wide range of audio signals to be represented accurately within the constraints of the 16-bit format.
